// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFiler(arg1:string,arg2:string):Promise<main.ProcessResult>;

export function GetConfig():Promise<main.Config>;

export function ProcessFiles(arg1:string,arg2:string):Promise<main.ProcessResult>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SelectFolder(arg1:string):Promise<string>;
